
// 사람 객체
const person = {
  age: 30,
  name: "둘리",
  address: "서울"
};

// 사람 객체의 정보를 수정
person.age = 10;
person.name = "또치";
person.address = "인천";

// 수정된 사람 객체 출력
console.log(`이름: ${person.name}, 나이: ${person.age}, 주소: ${person.address}`);

// 제품 객체
const product = {
  name: "노트북",
  price: 1500000,
  brand: "삼성"
};

// 제품 객체의 정보를 수정
product.name = "데스크탑";
product.price = 2000000;
product.brand = "LG";

// 수정된 제품 객체 출력
console.log(`제품명: ${product.name}, 가격: ${product.price}원, 브랜드: ${product.brand}`);


